# Generated by Django 5.1.6 on 2025-02-21 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template', models.CharField(max_length=100)),
                ('sections', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#ffffff', max_length=7)),
                ('accent_color', models.CharField(default='#007bff', max_length=7)),
                ('heading_font', models.CharField(default='Arial', max_length=100)),
                ('body_font', models.CharField(default='Arial', max_length=100)),
                ('section_settings', models.JSONField(default=dict)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_customization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
