services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3333:3333"
    volumes:
      - ./nginx-local.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/staticfiles:ro
  db:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    expose:
      - 5432
    ports:
      - 35432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  postgres_data:
  
