# Generated by Django 5.1.4 on 2025-01-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subcategory', models.TextField()),
                ('fieldType', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], default='text', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creator', models.TextField()),
                ('store', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('finalized', 'Finalized'), ('reserved', 'Reserved')], default='draft', max_length=9)),
                ('referenceNumber', models.TextField()),
                ('manufacturer', models.TextField()),
                ('model', models.TextField()),
                ('location', models.TextField()),
                ('availability', models.TextField()),
                ('condition', models.TextField()),
                ('timeOfCreation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booleanContents', models.BooleanField()),
                ('textContents', models.TextField()),
                ('numberContents', models.DecimalField(decimal_places=2, max_digits=10)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fielddefinition')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fields', to='shop.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='listing',
            name='productCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='productCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='shop.productcategory'),
        ),
    ]
