# Generated by Django 5.1.4 on 2025-01-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_listing_availability_alter_listing_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='subcategory',
            field=models.CharField(verbose_name=128),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
