# Generated by Django 5.1.4 on 2025-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_fielddefinition_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='subcategory',
            field=models.CharField(max_length=128),
        ),
    ]
