# Generated by Django 5.1.4 on 2025-01-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_listingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='contentType',
            new_name='mimetype',
        ),
    ]
