# Generated by Django 5.1.5 on 2025-02-14 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_introduce_RLS'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('data', models.BinaryField(editable=True)),
                ('mimetype', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunSQL("delete from shop_listingimage"),
        migrations.RemoveField(
            model_name='listingimage',
            name='data',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='fileName',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='mimetype',
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shop.image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
                ('sites', models.ManyToManyField(related_name='shops', to='sites.site')),
            ],
        ),
    ]
