# Generated by Django 5.1.5 on 2025-02-17 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_add_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='shop.shop'),
        ),
    ]
